### ISSUE TITLE
How do I disable "Incorrect list-item indent: add 2 spaces" from Atom's config.cson?

### ISSUE THREAD

**Issue by HebaruSan** [AtomLinter/linter-markdown#150]
I tried this, plus a few other variants, but these warnings still appear:

```
  remark:
    plugins:
      "remark-lint":
        "list-item-indent": false
  "remark-lint":
    "list-item-indent": false
```

What's the right way to disable them?
